### ISSUE TITLE
M1 Mac（Appleシリコン）でdocker-compose upするとエラーになる

### ISSUE THREAD

**Issue by takatama** [coderdojo-japan/coderdojo.jp#1548]
MacBook Air M1を使っています。docker-compose up を実行すると次のエラーになります。
https://ksss9.hatenablog.com/entry/2021/02/08/002737 によると、M1 Macではentrykitが使えないそうです。

```
1.555 2023-07-14 15:49:53 (4.56 MB/s) - ‘entrykit_0.4.0_Linux_x86_64.tgz’ saved [2708228/2708228]
1.555 
1.565 entrykit
1.639 runtime: failed to create new OS thread (have 2 already; errno=22)
1.640 fatal error: newosproc
1.642 
1.642 runtime stack:
1.642 runtime.throw(0x84a820, 0x9)
1.643 	/usr/local/go/src/runtime/panic.go:527 +0x90
1.643 runtime.newosproc(0xc820028000, 0xc820037fc0)
1.643 	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
1.643 runtime.newm(0x8e5980, 0x0)
1.643 	/usr/local/go/src/runtime/proc1.go:1105 +0x130
1.643 runtime.main.func1()
1.643 	/usr/local/go/src/runtime/proc.go:48 +0x2c
1.643 runtime.systemstack(0xa2b6e0)
1.643 	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
1.643 runtime.mstart()
1.643 	/usr/local/go/src/runtime/proc1.go:674
1.644 
1.644 goroutine 1 [running]:
1.644 runtime.systemstack_switch()
1.644 	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820022770 sp=0xc820022768
1.644 runtime.main()
1.644 	/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200227c0 sp=0xc820022770
1.644 runtime.goexit()
1.644 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200227c8 sp=0xc8200227c0
------
failed to solve: process "/bin/sh -c wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz     && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz     && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz     && mv entrykit /bin/entrykit     && chmod +x /bin/entrykit     && entrykit --symlink" did not complete successfully: exit code: 2
```

**Comment by takatama** [comment]
修正案があります。PRを作ってみます。

**Comment by takatama** [comment]
#1549 でマージされました 👏
