### ISSUE TITLE
bin/rake dojos:update_db_by_yamlが失敗する

### ISSUE THREAD

**Issue by nalabjp** [coderdojo-japan/coderdojo.jp#230]
ローカルではコケる。
dojos.idがユニークじゃない、とのこと。

```
$ bin/rake dojos:update_db_by_yaml
rake aborted!
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: dojos.id: INSERT INTO "dojos" ("id", "name", "email", "order", "description", "logo", "url", "tags", "created_at", "updated_at", "prefecture_id") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `to_a'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `block (2 levels)in exec_query'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:209:in `block in exec_query'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:208:in `exec_query'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:102:in `exec_insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation.rb:61:in `insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:589:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/counter_cache.rb:178:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/locking/optimistic.rb:76:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:296:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:340:in `block in _create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:340:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/timestamp.rb:95:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:563:in `create_or_update'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `create_or_update'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:162:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/validations.rb:50:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `block in save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/suppressor.rb:46:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/lib/tasks/dojos.rake:44:in `block (3 levels) in <top (required)>'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/lib/tasks/dojos.rake:29:in `each'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/lib/tasks/dojos.rake:29:in `block (2 levels) in <top (required)>'

Caused by:
SQLite3::ConstraintException: UNIQUE constraint failed: dojos.id
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `to_a'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `block (2 levels)in exec_query'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:209:in `block in exec_query'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:208:in `exec_query'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:102:in `exec_insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation.rb:61:in `insert'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:589:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/counter_cache.rb:178:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/locking/optimistic.rb:76:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:296:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:340:in `block in _create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:340:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/timestamp.rb:95:in `_create_record'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:563:in `create_or_update'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `create_or_update'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:162:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/validations.rb:50:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `block in save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/suppressor.rb:46:in `save!'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/lib/tasks/dojos.rake:44:in `block (3 levels) in <top (required)>'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/lib/tasks/dojos.rake:29:in `each'
/Users/kimuraaaaa/ghq/github.com/nalabjp/coderdojo.jp/lib/tasks/dojos.rake:29:in `block (2 levels) in <top (required)>'
Tasks: TOP => dojos:update_db_by_yaml
(See full trace by running task with --trace)
```

## why?

[このコミット](https://github.com/coderdojo-japan/coderdojo.jp/commit/36637fe77e7c15c319d2e687dc63e4ce4aef616e)で`Dojo#name`が変更されているが、

Dojoのupsertではnameをキーに既存のレコードを引っ張ってきているので、
`Dojo#name`を変更すると新規レコードとしてDojoのインスタンスが生成される。
https://github.com/coderdojo-japan/coderdojo.jp/blob/7712b8a6dfa9f746d87d4e470119ad50017b537f/lib/tasks/dojos.rake#L30

しかし、dojosテーブルのidとしては52は既に使われているのでinsert時にユニーク制約に引っかかっている模様。

# production

本番データを確認してみたけど、本番は問題なさそうだった。（なぜ？🤔）
<img width="1597" alt="2018-01-02 12 28 30" src="https://user-images.githubusercontent.com/1544172/34473768-15bbf730-efba-11e7-89bb-25ae8118be75.png">

**Comment by yasulab** [comment]
こちら回答が遅くなりましたが、名称変更のコミット後、僕の方で本番環境にアクセスして直接renameした覚えがあります 💦

**Comment by nalabjp** [comment]
なるほど、把握しました！☺️
