### ISSUE TITLE
Fb API の仕様変更で統計スクリプトが失敗しているので、Fb Groups 権限取得用アプリの申請をしてみた

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#371]
@chicaco さんにご対応してただけることになりました...!! ありがとうございます (＞人＜ )✨
cf. https://github.com/coderdojo-japan/coderdojo.jp/pull/297#issuecomment-451744226

## やること

- [x] 統計スクリプトを直す 

> TODO のコメントが fix されていたように見えたので消しちゃってましたが、これを revert すれば直りそう? 🤔💭
> https://github.com/coderdojo-japan/coderdojo.jp/commit/e0b6c5bc1554e2fe119ad8498e11ce3fc6c0f7e7#diff-8b7db4d5cc4b8f6dc8feb7030baa2478L36

- [ ] 2018/12/03〜2018/12/31 までの統計情報も本番環境で集計する

> 
![image](https://user-images.githubusercontent.com/155807/50967813-95eb3c80-151c-11e9-9c6d-cbade7d4abb0.png)

**Comment by chicaco** [comment]
Gemfile に `gem 'faraday_middleware'` を追記してみましたが、
`$ bin/rake statistics:aggregation[2012,2013]` でまだエラーが...。

```
2012/01~2013/12のイベント履歴の集計でエラーが発生しました
the server responded with status 504
./vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
./vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
./vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
./vendor/bundle/ruby/2.6.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
./vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
./vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
./vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
./lib/event_service/client.rb:11:in `get'
./lib/event_service/providers/connpass.rb:25:in `block in fetch_events'
./lib/event_service/providers/connpass.rb:24:in `loop'
./lib/event_service/providers/connpass.rb:24:in `fetch_events'
./lib/statistics/tasks/connpass.rb:17:in `block (2 levels) in run'
...
```

lib/event_service/providers/doorkeeper.rb で起きることもあり、サクッと解決とはならず。 😢 

504 Gateway Timeout ですから、タイミングか制限(?)か...。
本日は time up です。 💦

**Comment by chicaco** [comment]
@yasulab 本番環境のログに、エラー情報残っていないでしょうか？

週/月ごとに GET でなく、Dojo ごとに期間指定で一括 GET する方式に切り替えようと考えております。

**Comment by yasulab** [comment]
@chicaco 本番環境も同じRailsアプリケーションなので、ローカル環境でうまく動けば本番環境でも基本的にうまく動くと思います! (違いは環境変数ぐらいかな🤔)

**Comment by chicaco** [comment]
@yasulab poduction 環境ですと Gem の構成が異なると思います。
faraday_middleware は develop & test では install されますが、production では入らないはずで、
本当に faraday_middleware は無関係かどうかまだ確証がなく。
(今夜にでも調べてみるつもりですが)

**Comment by yasulab** [comment]
> poduction 環境ですと Gem の構成が異なると思います

@chicaco `RAILS_ENV=production` で本番環境と同じ Gem の構成にできます...!! d(￣ ￣)✨

**Comment by chicaco** [comment]
> `RAILS_ENV=production` で本番環境と同じ Gem の構成にできます...!! d(￣ ￣)✨

はい、その手で調べてみるつもりでおります。

**Comment by yasulab** [comment]
👍

**Comment by nalabjp** [comment]
faraday_middlewareが必要な理由はココですね。
https://github.com/coderdojo-japan/coderdojo.jp/blob/bc8c539e12f3a216a90132869f167c339749ea2b/lib/event_service/client.rb#L19
この指定で`FaradayMiddleware::ParseJson`を使うように指定しています。

**Comment by nalabjp** [comment]
アプリレビューの話は特に何も対応していなかったら引っかかってそうなので怪しそうですね。

レートリミットはこれですかね。
coderdojoのアプリについては僕も管理者権限を持っていないので @yasulab にお願いしないとわからなさそうです。
https://developers.facebook.com/docs/graph-api/advanced/rate-limiting?locale=ja_JP

あと、ここからcoderdojoのアプリを検索するとなにか出てきたりしますでしょうか？
https://developers.facebook.com/tools/api_versioning/
facebookログインはAPIバージョンをあげないといけないのが去年あったような気がするのでこちらもなにかでてくるかもしれません。

**Comment by yasulab** [comment]
> あと、ここからcoderdojoのアプリを検索するとなにか出てきたりしますでしょうか？
> https://developers.facebook.com/tools/api_versioning/

確認しました! ✅  他の version (v2.9~v3.1) も調べてみましたが、すべて下記のように表示されました 👀

![image](https://user-images.githubusercontent.com/155807/51507157-f0489f00-1e32-11e9-8b20-f3e4032b4655.png)

**Comment by yasulab** [comment]
> あと、ここからcoderdojoのアプリを検索するとなにか出てきたりしますでしょうか？
> https://developers.facebook.com/tools/api_versioning/

確認しました! ✅  他の version (v2.9~v3.1) も調べてみましたが、すべて下記のように表示されました 👀

![image](https://user-images.githubusercontent.com/155807/51507157-f0489f00-1e32-11e9-8b20-f3e4032b4655.png)

**Comment by yasulab** [comment]
> facebookログインはAPIバージョンをあげないといけないのが去年あったような気がする

あー、多分これな気がしますね 💦 必要な情報を入力して提出します! 📝 💨  (2018年8月から Facebook イベントの統計情報は取れてなさそう 😅 )
![image](https://user-images.githubusercontent.com/155807/51507378-02770d00-1e34-11e9-9d3b-9a4db8ca5411.png)

**Comment by yasulab** [comment]
なるほど2018年から今回のような統計情報目的の API Call も App Review 必須になったんですね🤔💭
![image](https://user-images.githubusercontent.com/155807/51507679-51717200-1e35-11e9-95ae-175cf42c6dd8.png)

@nalabjp @chicaco ひとまず Group API の Request を提出しておきました! 📜 📝 💨 

![image](https://user-images.githubusercontent.com/155807/51507803-f724e100-1e35-11e9-869d-574dc1846204.png)

cf. https://developers.facebook.com/docs/apps/review#app-review

## 提出情報

### Tell us how you're using this permission or feature
CoderDojo Japan provides Stats page ( https://coderdojo.jp/stats ) that visually show two numbers, how many times CoderDojo events take place and how many people attend the events. We only use the two numbers for stats page, and never publish any personal information such as who hosted the events and who attends there.

### Demonstrate how your selected platforms will use this permission or feature: Web

1. Go to CoderDojo Japan's Stats page: https://coderdojo.jp/stats 
2. See the three visual graphs; number of CoderDojos, number of events, and number of participants.

NOTE: There are no interfaces for users to use this app. This app is only used by developers of CoderDojo Japan website.

### Show us how you're using this permission or feature

![coderdojo japan stats screencast](https://user-images.githubusercontent.com/155807/51508721-dd859880-1e39-11e9-8e30-47b247f106ac.gif)

### Done ✅ 

![image](https://user-images.githubusercontent.com/155807/51508773-16be0880-1e3a-11e9-9ddc-18f743291f78.png)

**Comment by yasulab** [comment]
了解です! 結果が出たらこちらでまた共有しますね〜 d(￣ ￣)✨

**Comment by chicaco** [comment]
> faraday_middlewareが必要な理由はココですね。
>   :
> この指定で`FaradayMiddleware::ParseJson`を使うように指定しています。

Gemfile に記載されていた以下のコメント：

```
# TODO: Delete this if the following issue is fixed
# https://github.com/bundler/bundler/issues/5332
```

ではなくて、「使っているから必要」という理由だったのですね。
その観点失念していました...、申し訳ありません ＆ ご指摘ありがとうございます！ > @nalabjp

**Comment by chicaco** [comment]
> アプリレビューの話は特に何も対応していなかったら引っかかってそうなので怪しそうですね。

facebook については、アプリレビュー結果待ちで。 🙇‍♀️ 

connpass は今かなり不安定な状態なようです。
現時点でも、成功, 502 を繰り返しています...。
参考 → https://twitter.com/connpass_jp/status/1087622617522008064

**Comment by nalabjp** [comment]
@chicaco 
いえいえ、当該行のコミットを入れたときに僕がTODOコメントを消しておけば良かったのかなと思います🙈

**Comment by chicaco** [comment]
整理させてください。 > @yasulab @nalabjp 

問題点：
(1) 2018/12/03 以降で統計スクリプトが失敗していた理由は、faraday_middleware を外してしまったから。
(2) プロバイダによってレート制限がある。
(3) (1) とは別に、facebook api のアプリレビューができていなかった問題があった。(2018/08 以降)
(4) 502,504 エラーが出ることがある。

#375 の PR で対応する範囲は、(1),(2) でよろしいでしょうか？

(3) はアプリレビュー待ちとして、必要であれば別 PR 化となるでしょうか。(トークンは環境変数で設定している？？)

(4) については、失敗したときのリトライというかリカバリ方法を検討する必要があると思います。
大掛かりな改修(プロバイダごとに「前回成功日時」を保存するような仕組みなど？)になりそうですし、(1),(2) の範囲は先行して改修しておりこの範囲の PR でマージする意味もありますので、(1),(2),(3) とは独立した問題として別 issue & PR にした方がよいと思います。
いかがでしょうか？

**Comment by nalabjp** [comment]
一点だけ気になっていて、
レートリミットの対応がdojo毎の取得となるとAPIコールの回数が寧ろ増えるケースが出てくるのではと思っているんですが、
対応方針の認識に齟齬がありますでしょうか？

ref: https://github.com/coderdojo-japan/coderdojo.jp/pull/375#issuecomment-456319828

**Comment by chicaco** [comment]
> 一点だけ気になっていて、
> レートリミットの対応がdojo毎の取得となるとAPIコールの回数が寧ろ増えるケースが出てくるのではと思っているんですが、
> 対応方針の認識に齟齬がありますでしょうか？
> 
> ref: [#375 (comment)](https://github.com/coderdojo-japan/coderdojo.jp/pull/375#issuecomment-456319828)

修正前の実装では、期間(週 or 月) × dojo ごとに GET していましたので、
期間をできるだけまとめて(connpass は期間指定が特殊なので一括にならないこともあるが、一週間、1ヶ月や一年の指定では一括にできます) dojo ごとにしていますので、期間の繰り返し分、API コールの回数が減ります。

> それ以外は良さそうに思います〜😌

ありがとうございます！ 😄

**Comment by nalabjp** [comment]
あぁ、やっと理解できたかもしれないんですが、
例えば3週間分取得したかった時に「1週間分x3回」で取得していたのが「3週間分x1回」でよくなる、ということだったりしますか？

**Comment by chicaco** [comment]
> 例えば3週間分取得したかった時に「1週間分x3回」で取得していたのが「3週間分x1回」でよくなる、ということだったりしますか？

はい、その通りです！
少なくても facebook と doorkeeper は。
(説明が下手で済みません 😓 )

**Comment by yasulab** [comment]
文章の書き方の話になっちゃいますが、なるべくカッコを使わずに文章を書くと伝わりやすい文章になるかもしれないです ;)

cf. [数学文章作法のススメ（全文公開された第１章より一部引用） - Qiita:Team](https://yasslab.qiita.com/yasulab/items/8ac3e2adc09c6337d511)

ご参考になれば (＞人＜ )✨

**Comment by nalabjp** [comment]
なるほど、範囲指定できる方に合わせるように仕様を変えたんですね。
仕様変更の意図は理解しました。

**Comment by chicaco** [comment]
@yasulab facebook のアプリレビューに関連して、お願いがあります。
CoderDojo Japan のアプリの設定で、「役割」の「開発者」か「テスター」に自分を追加していただけないでしょうか？ アプリレビューが通れば、自アカウントのトークンを使って、ローカル環境で動確可能になると思っております。 🙏

**Comment by yasulab** [comment]
> 「役割」の「開発者」か「テスター」に自分を追加

@chicaco こちら「開発者」で追加しておきました...!! 後ほど通知が届くと思うので受理してもらえれば  (＞人＜ )✨
(合わせて @nalabjp さんも Facebook の CoderDojo Japan App に追加しておきました 📨 )

**Comment by yasulab** [comment]
Reject されたんですが理由がちょっとわからなかったので Ask a new question した! ✅ 😭 

![image](https://user-images.githubusercontent.com/155807/51722798-fc826580-2099-11e9-9e63-a0ad69d1f6af.png)

**Comment by yasulab** [comment]
@nalabjp 問い合わせした結果「Groups API のユースケースと違うから Reject したよ」という回答でした 👀💦 Groups API 以外の実装方法を考えるか、もしくは下記に回答できる方法を考える必要がありそうですね 🤔💭 cc/ @chicaco 

> **Comment:** Hello Yohei,
> 
> Thank you for contacting Direct Support.
> 
> With regards to your feedback, you do not show a proper use case of the Groups API permission in your screencast. 
> 
> The Groups API permission is meant for developers to: help people manage the posts, content, and likes published to their group, help people get information about content posted to in their group, let people publish content from your app to their Facebook group, and help people get aggregated insights about activity happening in their group.
> 
> Please show how you will use one of these features in your screencast.
> 
> Best regards,

**Comment by chicaco** [comment]
@yasulab @nalabjp 統計情報で求められる条件を満たすのは難しそうですが、他に統計情報を自動で収集する策が今のところ思い付きません...。
が、これから実装しようとしている #258 & #297「直近のイベント情報を収集＆一覧表示 → グループ周知と集客」で条件を満たすような気がします。
いかがでしょう？ 作戦変更でリトライできないでしょうか？
これから実装する機能なのでまだスクショは撮れませんが。

**Comment by chicaco** [comment]
これは援護射撃にならないでしょうか？
https://news.coderdojo.jp/2018/10/12/press-support-facebook-coupon/
🤔

**Comment by yasulab** [comment]
> これから実装しようとしている #258 & #297「直近のイベント情報を収集＆一覧表示 → グループ周知と集客」で条件を満たすような気がします。

@chicaco 素晴らしいアイデアありがとうございます! 😆 確かにこのアイデア良さそうですね...!! (＞人＜ )✨

Groups API に関する回答を整理すると、次のユースケースのいずれかに該当することだと整理できますが、上記のロジックだと「2. と 4. に該当する」というロジックが成り立ちそうなですね ;)

1. help people manage the posts, content, and likes published to their group
2. **help people get information about content posted to in their group**
3. let people publish content from your app to their Facebook group
4. **help people get aggregated insights about activity happening in their group**

おっしゃる通り現在は未実装実装ですが、いずれにせよ Groups API にアクセスできなければ取得できない情報なので、まずは実際に取得するデータを手動で取得＆表示して、その Screenshot や Screencast を持って再提出するのが良さそうですね ;) 

少し遠回りになってしまいますが、このアプローチは良いと思いうので、「 **手動で** 一部の直近のイベント情報を収集し、それを表示する」という部分だけ進めて見ていただけると嬉しいです...!! (＞人＜ )✨

🤔.oO(もしくは僕が知らないだけで、データを取得するだけだったらアプリの申請をしなくても出来たりするのかなぁ? そうでないと `Please show how you will use one of these features in your screencast.` ってモックでしか作りようがないと思うので)

**Comment by nalabjp** [comment]
お、いい案ですねー 👍 

> そうでないと Please show how you will use one of these features in your screencast. ってモックでしか作りようがないと思う

そんな感じがするので、一旦テキストで「直近のイベント情報を収集＆一覧表示するから！」って言ってみるとなにかしら回答くれたりしないですかねぇ？

**Comment by yasulab** [comment]
> 一旦テキストで「直近のイベント情報を収集＆一覧表示するから！」って言ってみるとなにかしら回答くれたりしないですかねぇ？

うーん、Attachments が要求されるっぽいので、デザインだけでも大丈夫かもですがモックがないと難しそう...? 🤔💭

**Comment by chicaco** [comment]
@yasulab @nalabjp
空いた時間にちょっと調べていたりしたのですが、
アプリはテストユーザでテストできる、とされています。
https://developers.facebook.com/docs/apps/test-users

ただし、アプリが「開発モード」でないとアクセス制限には引っかかるので、テストはアプリの設定を引き継いだテストアプリで行う、と書かれています。
https://developers.facebook.com/docs/apps/test-apps

また、グループのイベントを取得する API では、アプリレビューの他に、そのグループにアプリをインストールしてもらわないとだめそうです。
https://developers.facebook.com/docs/graph-api/reference/v3.2/group/events

もう一点、CoderDojo のアプリレビューは、「サーバー間アプリ」になるのでは、と気付きました。
https://developers.facebook.com/docs/apps/review/server-to-server-apps/

いろいろ調べ切れておらず、五月雨の情報で済みません。

**Comment by yasulab** [comment]
特に誰かにインストールしてもらってもらう類のものではないので、ひとまず Development Mode に戻しておきました ✅ これで Groups API を試せるようになるのかな...? 👀cc/ @chicaco @nalabjp 
![image](https://user-images.githubusercontent.com/155807/51826054-7da35c00-2329-11e9-819f-99c6e8f35fbe.png)

**Comment by chicaco** [comment]
報告が滞ってしまい、済みません。
現状 2 点ほど。

(1) connpass

サイト内の検索機能は閉鎖中で、APIからの検索機能も超不安定です。
ほぼ検索不能な状態...。

サイトの先頭に下記のお知らせが掲載されています。

<img width="1063" alt="connpass_info" src="https://user-images.githubusercontent.com/1582945/52567104-d35e2500-2e4e-11e9-90e2-50b54dca4a82.png">

(2) facebook

まだスッキリ整理できていないのですが、途中経過です。

----

# facebook of developers グラフAPIエクスプローラ による調査

以下の 3 グループについて確認
- A : Ohno Chicaco が参加していない公開グループ (CoderDojo 博多)
- B : Ohno Chicaco が参加している公開グループ
- C : Ohno Chicaco がオーナなグループ

## GET /v3.2/{group-id}

グループ情報の取得

|アプリ|A|B|C|
|---|---|---|---|
|CoderDojo Japan|OK|NG (GraphMethodException)|OK|
|CoderDojo Japan - Test1|NG(OAuthException)|NG (GraphMethodException)|OK|
|CD_TEST|NG(OAuthException)|NG (GraphMethodException)|OK|

(C) に対し、アプリをアンインストールし、アプリのテストユーザのトークンでリトライするとすべて NG (GraphMethodException)

## GET /v3.2/{group-id}/events

グループイベント情報の取得
※ sinse/until でイベントが存在する期間を指定

|アプリ|A|B|C|
|---|---|---|---|
|CoderDojo Japan|{ "data": [] }|NG (GraphMethodException)|OK|
|CoderDojo Japan - Test1|{ "data": [] }|NG (GraphMethodException)|OK|
|CD_TEST|{ "data": [] }|NG (GraphMethodException)|OK|

(C) に対し、アプリをアンインストールし、アプリのテストユーザのトークンでリトライするとすべて NG (GraphMethodException)

## NG の例

1. OAuthException

~~~~
{
  "error": {
    "message": "(#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.",
    "type": "OAuthException",
    "code": 10,
    "fbtrace_id": "Cj0vOl598AU"
  }
}
~~~~

2. GraphMethodException

~~~~
{
  "error": {
    "message": "Unsupported get request. Object with ID '772583502854357' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
    "type": "GraphMethodException",
    "code": 100,
    "error_subcode": 33,
    "fbtrace_id": "D3O+LsgLsDb"
  }
}
~~~~

## MEMO

グラフAPIエクスプローラ でなく postman でやってみると、結果が違うかも。
要確認！

**Comment by yasulab** [comment]
> 4\. **help people get aggregated insights about activity happening in their group**

「[近日開催のイベント](https://coderdojo.jp/events)」ができたので、「Please show how you will use one of these features in your screencast.」を提出することができそう 🤔💭

ここのページに Facebook Events も追加することで Facebook Groups API の使用要件である「help people get aggregated insights about activity happening in their group」を満たすと思うのですがいかがでしょう...? 的な方向で再度申請してみようと思います 📮 🏃💨
