### ISSUE TITLE
SoundCloud のテストがリポジトリ間の PR で失敗する原因を調査する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#500]
#499 の PR の CI 結果を見ると、Travis CI 上に SoundCloud の環境変数が設定されていないのかも...? 👀 💭 cc/ @chicaco 

cf. https://travis-ci.org/coderdojo-japan/coderdojo.jp/builds/562582067#L606-L630
```bash
近日開催イベント情報を収集しました
.==== START soundcloud_tracks:upsert ====
F==== START soundcloud_tracks:upsert ====
F==== START soundcloud_tracks:upsert ====
F
Failures:
  1) soundcloud_tracks soundcloud_tracks:upsert 単純更新
     Failure/Error: client = SoundCloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'])
     
     ArgumentError:
       At least a client_id or an access_token must be present
     # ./lib/tasks/soundcloud_tracks.rake:10:in `block (2 levels) in <top (required)>'
     # ./spec/lib/tasks/soundcloud_tracks_spec.rb:104:in `block (3 levels) in <top (required)>'
  2) soundcloud_tracks soundcloud_tracks:upsert 単純追加
     Failure/Error: client = SoundCloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'])
     
     ArgumentError:
       At least a client_id or an access_token must be present
     # ./lib/tasks/soundcloud_tracks.rake:10:in `block (2 levels) in <top (required)>'
     # ./spec/lib/tasks/soundcloud_tracks_spec.rb:57:in `block (3 levels) in <top (required)>'
  3) soundcloud_tracks soundcloud_tracks:upsert 複数 (追加/更新)
     Failure/Error: client = SoundCloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'])
     
     ArgumentError:
       At least a client_id or an access_token must be present
     # ./lib/tasks/soundcloud_tracks.rake:10:in `block (2 levels) in <top (required)>'
     # ./spec/lib/tasks/soundcloud_tracks_spec.rb:165:in `block (3 levels) in <top (required)>'
```

**Comment by chicaco** [comment]
直前の PR まではエラーなく CI が通っていますし、必要な環境変数は `.travis.yml` で設定済みの認識です。 🤔

**Comment by yasulab** [comment]
リポジトリ間の PR で失敗しているのかもですねー。タイトル修正しておきました 🔧 💨

**Comment by chicaco** [comment]
PR [#540 必要な環境変数が設定されていないときは SoundCloud のテストをスキップする](https://github.com/coderdojo-japan/coderdojo.jp/pull/540) で対処しました。

cf. #319, #352
